[package]
name = "rusty_raisr"
version = "0.1.0"
authors = ["Srinivas Kaza <srinivas@kaza.io>"]

[dependencies]
nalgebra = "0.16.0"
image = "0.19.0"
#torchrs = { git = "https://github.com/torchrs/torchrs.git" }